Azure-App-Service/ImageBuilder

- GenerateDockerFiles/KuduLite/template/kudu/Dockerfile
pin clamav version to supported by debian9
> fix kudulite

- BuildAndTagImages/build.sh
- BuildAndTagImages/buildImageJob.yml
Integrates pushing Images to MCR for the CI Pipeline
> Modified to push to MCR for CI Pipeline

- GenerateDockerFiles/dockerFilesGenerateTask.yml
- GenerateDockerFiles/dotnetcore/debian-9/init_container.sh
- GenerateDockerFiles/node/debian-9/startup/init_container.sh
- GenerateDockerFiles/php/apache/init_container.sh
- GenerateDockerFiles/python/template-2.7/init_container.sh
- GenerateDockerFiles/python/template-3.6/init_container.sh
- GenerateDockerFiles/python/template-3.7/init.py
- GenerateDockerFiles/python/template-3.7/init_container.sh
- GenerateDockerFiles/python/template-3.8/init.py
- GenerateDockerFiles/python/template-3.8/init_container.sh
cc @sanchitmehta @arroyc @qianz2
> Updated runtime images startup script command

- GenerateDockerFiles/dockerFilesGenerateTask.yml
This oryx base image contains the dependencies needed for the GDI library in dotnetcore.
> Updated oryx base image tag for GDI library

- GenerateDockerFiles/python/template-2.7/Dockerfile
- GenerateDockerFiles/python/template-2.7/init_container.sh
- GenerateDockerFiles/python/template-3.6/Dockerfile
- GenerateDockerFiles/python/template-3.6/init_container.sh
- GenerateDockerFiles/python/template-3.7/Dockerfile
- GenerateDockerFiles/python/template-3.7/init_container.sh
- GenerateDockerFiles/python/template-3.8/Dockerfile
- GenerateDockerFiles/python/template-3.8/init_container.sh
This PR will enable a python virtual env on ssh into the container. Any libraries added to this venv will be available to the app.
> Enable python virtual env

- Config/nodeVersionTemplateMap.txt
- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localGenerateDockerFiles.sh
> add node 14

- GenerateDockerFiles/python/template-2.7/Dockerfile
- GenerateDockerFiles/python/template-2.7/init_container.sh
- GenerateDockerFiles/python/template-3.6/Dockerfile
- GenerateDockerFiles/python/template-3.6/init_container.sh
- GenerateDockerFiles/python/template-3.7/Dockerfile
- GenerateDockerFiles/python/template-3.7/init_container.sh
- GenerateDockerFiles/python/template-3.8/Dockerfile
- GenerateDockerFiles/python/template-3.8/init_container.sh
Removing activation of python venv on ssh.
> Remove python venv

- Release/release.sh
- Release/release.yml
Reverts Azure-App-Service/ImageBuilder#59
> Revert "release.sh consumes build#"

- BuildAndTagImages/build.sh
- Tests/KuduLite/HelloWorld.cs
- Tests/KuduLite/Tests.csproj
- Tests/KuduLite/dotnetcore/repository/Program.cs-tmp
- Tests/KuduLite/dotnetcore/repository/Startup.cs-tmp
- Tests/KuduLite/dotnetcore/repository/appsettings.Development.json
- Tests/KuduLite/dotnetcore/repository/appsettings.json
- Tests/KuduLite/dotnetcore/repository/dotnetcore31web.csproj
- Tests/KuduLite/node/repository/index.js
- Tests/KuduLite/node/repository/package.json
- Tests/node/express-app/index.js
- Tests/node/express-app/package.json
- localBuildDockerImages.sh
- localRunTests.sh
- localSetupTests.sh
test kudu build with dotnetcore and node
> add kudulite build app test

- GenerateDockerFiles/python/template-2.7/init_container.sh
- GenerateDockerFiles/python/template-3.6/init_container.sh
- GenerateDockerFiles/python/template-3.7/init_container.sh
- GenerateDockerFiles/python/template-3.8/init_container.sh
Command should be in the format oryx create-script -debugAdapter ptvsd -debugPort 49494 -appPath /home/site/wwwroot.
> Fixed sequence of args when app debugging is true

- GenerateDockerFiles/node/node-template/startup/init_container.sh
- GenerateDockerFiles/node/pm2-template/startup/init_container.sh
Seems like some unknown oryx parameters are breaking node remote debugging
> fix node remote debugging

- GenerateDockerFiles/node/node-template/startup/init_container.sh
- GenerateDockerFiles/node/pm2-template/startup/init_container.sh
Reverts Azure-App-Service/ImageBuilder#82
> Revert "fix node remote debugging"

- GenerateDockerFiles/dockerFilesGenerateTask.yml
- GenerateDockerFiles/python/template-2.7/Dockerfile
- GenerateDockerFiles/python/template-3.6/Dockerfile
- GenerateDockerFiles/python/template-3.7/Dockerfile
- GenerateDockerFiles/python/template-3.8/Dockerfile
This PR adds a default value for the $APP_PATH and also changes the default Oryx Version to `20201112.1`
> Python Workflow Changes

- GenerateDockerFiles/dotnetcore/debian-9/hostingstart.html
- GenerateDockerFiles/dotnetcore/generateDockerfiles.sh
Added some comments
Removed unwanted new lines
> Change .NET branding if 5.0

- CI.yml
- GenerateDockerFiles/KuduLite/generateDockerfiles.sh
- GenerateDockerFiles/php-xdebug/8.0-apache-xdebug/Dockerfile
Changing dynamic kudu to buster based kudu.
Adding Xdebug 3.0.0 which supports PHP 8.0.
> Xdebug 3.0.0 supports PHP 8.0 and Buster Kudu

- GenerateDockerFiles/dotnetcore/debian-9/init_container.sh
Add dot-monitor collection port for Kudlite
> Add dot-monitor collection port

- Config/nodeVersionTemplateMap.txt
- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localGenerateDockerFiles.sh
Oryx update to 20210805.1 and Node 16 support
> Oryx update to 20210805.1 and Node 16 support

- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localGenerateDockerFiles.sh
Oryx Tag 20211207.1 contains changes needed for python code-profiler
> Update oryx tag 20211207.1

- GenerateDockerFiles/python/common/code_profiler/collect_trace.sh
Updating the helper message for code-profiler
> Updating the helper message for code-profiler

- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localGenerateDockerFiles.sh
Updating Oryx base tag to 20220216.1
> Updating Oryx base tag 20220216.1

- GenerateDockerFiles/dotnetcore/debian-9/init_container.sh
- GenerateDockerFiles/node/node-template/Dockerfile
- GenerateDockerFiles/node/node-template/run-diag.sh
- GenerateDockerFiles/node/node-template/startup/init_container.sh
- GenerateDockerFiles/node/pm2-template/Dockerfile
- GenerateDockerFiles/node/pm2-template/run-diag.sh
- GenerateDockerFiles/node/pm2-template/startup/init_container.sh
- GenerateDockerFiles/python/common/run-diag.sh
- GenerateDockerFiles/python/template-2.7/Dockerfile
- GenerateDockerFiles/python/template-2.7/init_container.sh
- GenerateDockerFiles/python/template-3.6/Dockerfile
- GenerateDockerFiles/python/template-3.6/init_container.sh
- GenerateDockerFiles/python/template-3.7/Dockerfile
- GenerateDockerFiles/python/template-3.7/init_container.sh
- GenerateDockerFiles/python/template-3.8/Dockerfile
- GenerateDockerFiles/python/template-3.8/init_container.sh
- GenerateDockerFiles/python/template-3.9/Dockerfile
- GenerateDockerFiles/python/template-3.9/init_container.sh
Adding code to run diagnostic agent for node and python stacks
> Start diagnostic server for python and node

- GenerateDockerFiles/python/template-2.7/Dockerfile
- GenerateDockerFiles/python/template-2.7/gunicorn.conf.py
- GenerateDockerFiles/python/template-3.6/gunicorn.conf.py
For python 2.7 and 3.6 , updating gunicorn to write master pid to file
> For python 2.7 and 3.6 , updating gunicorn to write master pid to file

- CI.yml
- GenerateDockerFiles/KuduLite/generateDockerfiles.sh
- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localBuildDockerImages.sh
- localGenerateDockerFiles.sh
Updating CI for release branch support
- In this PR, excluding automated PRs for every merge on release/* branch as it is cherry picked.
- Kudulite images can be created based on specific kudulite branch
- Updated necessary changes for local and CI.yaml
> Updating CI for release branch support

- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localGenerateDockerFiles.sh
Update oryx base image tag to 20220323.2 for .net 5,6,7 new runtimes
> Update oryx base image tag to 20220323.2

- CI.yml
Removing scheduled builds for releases/ant97 branch
> Removing scheduled builds releases/ant97 branch

- BuildAndTagImages/build.sh
- BuildAndTagImages/buildImageJob.yml
- GenerateDockerFiles/dockerFilesGenerateTask.yml
- GenerateDockerFiles/dotnetcore/generateDockerfiles.sh
- localBuildDockerImages.sh
- localGenerateDockerFiles.sh
Add support for Generating dockerfile and building images for specific framework and stacks
> Add support for Generating dockerfile and building images for specific framework and stacks

- GenerateDockerFiles/dockerFilesGenerateTask.yml
Fixing missing ) in dockerfilesGenerateTask.aml
> Fixing missing ) in dockerfilesGenerateTask.aml

- GenerateDockerFiles/dockerFilesGenerateTask.yml
Fetching stack name from parameter instead of variable in dockerfileGenerateTask.yml
> Fetching stack name from parameter instead of variables

- BuildAndTagImages/build.sh
- BuildAndTagImages/buildImageJob.yml
- GenerateDockerFiles/dockerFilesGenerateTask.yml
The image builder pipeline was throwing an error due to indentation in condition property.
Fixing this bug
> Updating the indentation of condition property in dockerfilesGenerateTask.yml

- CI.yml
- GenerateDockerFiles/KuduLite/generateDockerfiles.sh
- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localBuildDockerImages.sh
- localGenerateDockerFiles.sh
In this PR,
- updating Oryx base image tag which has bullseye based oryx build image.
- Adding scripts needed to generate Bullseye Kudulite Image
This change will be cherry picked to releases/ant98 branch
> Adding support for Kudulite Bullseye

- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localGenerateDockerFiles.sh
Updating Oryx tag to 20220510.2
This is cherry picked from https://github.com/Azure-App-Service/ImageBuilder/pull/278
> Updating Oryx tag to 20220510.2

- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localGenerateDockerFiles.sh
This Oryx tag contains May security fixes for .NET images
> Update Oryx base image to 20220519.2

- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localGenerateDockerFiles.sh
This tag 20220621.1 contains June dotnet patches
> Updating Oryx base image tag

- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localGenerateDockerFiles.sh
Updating Oryx tag to 20220629.2 which has dotnet june security patches
> Updating Oryx tag to 20220629.2

- GenerateDockerFiles/python/template-3.10/gunicorn.conf.py
- GenerateDockerFiles/python/template-3.7/gunicorn.conf.py
- GenerateDockerFiles/python/template-3.8/gunicorn.conf.py
- GenerateDockerFiles/python/template-3.9/gunicorn.conf.py
Fixing import error when code profiler is imported in gunicorn.conf.py
> Fixing import error

- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localGenerateDockerFiles.sh
php 7.4 bullseye deployment bug
> update base image

- GenerateDockerFiles/python/common/app_logs/appServiceAppLogs.py
Changed the format of the date in the logs that is causing issue with azure monitor. Also removed a logging statement which can cause high disk usage.
> AppServiceAppLogs Fix

- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localGenerateDockerFiles.sh
This tag has newer version of the following stack images
- PHP : 7.4.30
- .NetCore 7 preview 7
- Python pyodbc lib issue fixes
> Updating oryx tag to 20220812.1

- GenerateDockerFiles/wordpress/wordpress/Dockerfile
- GenerateDockerFiles/wordpress/wordpress_with_mariadb/Dockerfile
Update linux-headers command in dockerfile to resolve build error
> Fix Wordpress build error

- GenerateDockerFiles/python/template-3.10/gunicorn.conf.py
- GenerateDockerFiles/python/template-3.7/gunicorn.conf.py
- GenerateDockerFiles/python/template-3.8/gunicorn.conf.py
- GenerateDockerFiles/python/template-3.9/gunicorn.conf.py
Appservice app logs to use only one variable flag to indicate if import succeeded
> fix appservice applogs

- GenerateDockerFiles/python/template-3.10/gunicorn.conf.py
- GenerateDockerFiles/python/template-3.7/gunicorn.conf.py
- GenerateDockerFiles/python/template-3.8/gunicorn.conf.py
- GenerateDockerFiles/python/template-3.9/gunicorn.conf.py
Co-authored-by: Sarath chandra Bussa <sbussa@microsoft.com>
> fix appservice applogs (#339)

- Config/php-xdebugVersionTemplateMap.txt
> Fixing PHPXdebug tag name

- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localGenerateDockerFiles.sh
This tag contains fixes for fpm-based image
> Updating Oryx base image tag to 20220822.1

- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localGenerateDockerFiles.sh
This tag contains the fixes for python 3.10 and build images
> Updating oryx tag 20220823.1

- GenerateDockerFiles/dockerFilesGenerateTask.yml
- localGenerateDockerFiles.sh
This tag contains fixes for python pyodbc issue
> Updating oryx base tag 20220825.1

- BuildAndTagImages/build.sh
- BuildAndTagImages/buildImageJob.yml
- CI.yml
- GenerateDockerFiles/dockerFilesGenerateTask.yml
Updating pipeline to use central feed services.
Reference Kudulite PR: https://msazure.visualstudio.com/DefaultCollection/Antares/_git/AAPT-Antares-KuduLite/pullrequest/6585888?path=/nuget.config
> Updating pipeline to use central feed services

- GenerateDockerFiles/wordpress/wordpress/local_bin/entrypoint.sh
- GenerateDockerFiles/wordpress/wordpress/local_bin/w3tc_cdn_config.sh
- GenerateDockerFiles/wordpress/wordpress/wordpress_src/wordpress-azure/wp-config.php
- GenerateDockerFiles/wordpress/wordpress_with_mariadb/local_bin/entrypoint.sh
- GenerateDockerFiles/wordpress/wordpress_with_mariadb/local_bin/w3tc_cdn_config.sh
- GenerateDockerFiles/wordpress/wordpress_with_mariadb/wordpress_src/wordpress-azure/wp-config.php
Schedule AFD (with Blob Storage) configuration using cron job which updates wp-config file to override SITE_URL with AFD endpoint.
> WordPress enable AFD configuration

- GenerateDockerFiles/python/template-3.10/Dockerfile
- GenerateDockerFiles/python/template-3.10/init_container.sh
- GenerateDockerFiles/python/template-3.6/Dockerfile
- GenerateDockerFiles/python/template-3.6/init_container.sh
- GenerateDockerFiles/python/template-3.7/Dockerfile
- GenerateDockerFiles/python/template-3.7/init_container.sh
- GenerateDockerFiles/python/template-3.8/Dockerfile
- GenerateDockerFiles/python/template-3.8/init_container.sh
- GenerateDockerFiles/python/template-3.9/Dockerfile
- GenerateDockerFiles/python/template-3.9/init_container.sh
Co-authored-by: Sarath chandra Bussa <sbussa@microsoft.com>
> PYTHONPATH moved to init_container.sh (#350)

- Tests/KuduLite/HelloWorld.cs
- Tests/KuduLite/Tests.csproj
- Tests/dotnetcore/Tests.csproj
- Tests/node/Tests.csproj
- Tests/php/Tests.csproj
- Tests/python/Tests.csproj
Updating dotnet and docker.dotnet versions
> Updating dotnet and docker.dotnet versions

- GenerateDockerFiles/wordpress/wordpress/Dockerfile
- GenerateDockerFiles/wordpress/wordpress/local_bin/entrypoint.sh
- GenerateDockerFiles/wordpress/wordpress/local_bin/migrate.sh
- GenerateDockerFiles/wordpress/wordpress_with_mariadb/Dockerfile
- GenerateDockerFiles/wordpress/wordpress_with_mariadb/local_bin/entrypoint.sh
- GenerateDockerFiles/wordpress/wordpress_with_mariadb/local_bin/migrate.sh
Add a trigger to import DB when the following App Settings are enabled:
MIGRATION_IN_PROGRESS
MIGRATE_NEW_DATABASE_NAME
MIGRATE_MYSQL_DUMP_PATH
> WordPress: Migration utility

- Config/wordpressVersionTemplateMap.txt
Upgrades:
PHP: 8.0.11 to 8.0.25
alpine: 3.13 to 3.15
> update php version to latest

- BuildAndTagImages/build.sh
> fix build.sh

- GenerateDockerFiles/dockerFilesGenerateTask.yml
- GenerateDockerFiles/wordpress/wordpress/local_bin/entrypoint.sh
- GenerateDockerFiles/wordpress/wordpress/local_bin/migrate.sh
- GenerateDockerFiles/wordpress/wordpress_with_mariadb/local_bin/entrypoint.sh
- GenerateDockerFiles/wordpress/wordpress_with_mariadb/local_bin/migrate.sh
Changes:
-> Comment out kudulite build from ImageBUilder CI
-> Re-configure AFD, CDN or Blob storage if MIGRATE_RETAIN_WP_FEATURES app setting is set to true
-> reduce migration retry count to 3
Bug fixes:
Update error messages
Code Format
> Update WordPress migration script

- GenerateDockerFiles/wordpress/wordpress/nginx_conf/temp-server-installation.conf
- GenerateDockerFiles/wordpress/wordpress/nginx_conf/temp-server-maintenance.conf
Making all the sub-paths point to the root path (/) in maintenance page.
> Resolving nginx 404 issues for maintenance page

- BuildAndTagImages/build.sh
- Config/wordpressVersionTemplateMap.txt
- GenerateDockerFiles/dockerFilesGenerateTask.yml
Additional change:
commented out diagnostic server generateDockerFiles task to unblock ImageBuilder pipeline
> Build 8.0 tag for WordPress stack

- BuildAndTagImages/build.sh
- GenerateDockerFiles/wordpress/wordpress/local_bin/nginx_update_post_filesync.sh
Updating with the correct nginx configuration to fix PHPMyAdmin 404 issue.
> PhpMyAdmin Fix

- Config/wordpressVersionTemplateMap.txt
- GenerateDockerFiles/wordpress/wordpress/Dockerfile
- GenerateDockerFiles/wordpress/wordpress_with_mariadb/Dockerfile
PHP version : 8.0.25 ->8.0.27
alpine version: 3.15 -> 3.16
nginx version: 1.20.3 ->1.22.1
> Update php base image and nginx version

- Config/wordpressVersionTemplateMap.txt
Made changes to Upgrade php to v8.2.7 and Alpine to v3.17
> Upgrade php to v8.2.7 and Alpine to v3.17

- Config/wordpressVersionTemplateMap.txt
Upgrade php v8.0.29 -> 8.0.30,  php v8.2.5 -> 8.2.9 and alpine v3.16 -> v3.18
> Upgrade php and alpine versions

- GenerateDockerFiles/wordpress/wordpress/wordpress_src/wordpress-azure/wp-content/plugins/app_service_email/admin/mailer/class-azure_app_service_email-controller.php
added changes to display the email content as html instead of raw text.
> changes to display email as html content
